const commons = {
  아이디: 'User ID',
  약관에_동의: 'Agree to Terms',
  확인: 'Confirm',
  추천_여행지: 'Recommended Travel Destination',
  검색하기: 'Search',
  검색: 'Search',
  시군구_선택: 'Select Si Gun Gu',
  시도_선택: 'Select Si Do',
  여행지_설명: 'Travel Destination Description',
  홈페이지_주소: 'Website Address',
  주소: 'Address',
  연락처: 'Contact',
  여행지: 'Travel Destination',
  통합검색: 'Unified Search',
  행사기간: 'Event Period',
  행사명: 'Event Name',
  행사장소: 'Event Location',
  문의처: 'Contact Information',
  행사내용: 'Event Details',
  길찾기: 'Find Directions',
  예약하기: 'Make a Reservation',
  농촌체험_예약: 'Rural Experience Reservation',
  힐링_농촌_체험지: 'Healing Rural Experience Site',
  나의_예약현황: 'My Reservation Status',
  로고: 'Logo',
  조이팜의_추천: "JoyFarm's Recommendation",
  지역별_축제_정보: 'Festival Information by Region',
  내_위치_주변_여행지: 'Nearby Travel Destinations',
  주변_여행지_리스트: 'Nearby Travel Destinations List',
  커뮤니티: 'Community',
  여행후기: 'Travel Reviews',
  공지사항: 'Notices',
  QnA: 'Q&A',
  공지글로_등록하기: 'Register as Notice',
  검색어를_입력하세요: 'Please enter a search term',
  사이트_관리: 'Site Management',
  이미지_업로드: 'Upload Image',
  작성자를_입력하세요: 'Please enter the author',
  제목을_입력하세요: 'Please enter the title',
  내용을_입력하세요: 'Please enter the content',
  글_번호: 'Post Number',
  축제_내용: 'Festival Content',
  // 회원 관련
  이메일: 'Email',
  인증코드_전송: 'Send Verification Code',
  인증코드_입력: 'Enter Verification Code',
  인증코드: 'Verification Code',
  비밀번호: 'Password',
  비밀번호_확인: 'Confirm Password',
  회원명: 'Member Name',
  휴대전화번호: 'Mobile Phone Number',
  프로필_이미지: 'Profile Image',
  업로드: 'Upload',
  변경하기: 'Change',
  회원가입_약관에_동의합니다: 'Agree to Terms of Membership',
  재전송: 'Resend',
  다시입력: 'Re-enter',
  가입하기: 'Sign Up',
  확인된_이메일_입니다: 'Email Verified',
  이메일을_입력하세요: 'Please enter your email',
  이메일을_인증하세요: 'Please verify your email',
  인증코드를_입력하세요: 'Please enter the verification code',
  비밀번호를_입력하세요: 'Please enter your password',
  비밀번호가_정확하지_않습니다: 'The password is incorrect',
  비밀번호를_확인하세요: 'Please confirm your password',
  회원명을_입력하세요: 'Please enter your name',
  전화번호를_입력하세요: 'Please enter your phone number',
  회원가입_약관에_동의하세요: 'Please agree to the terms of membership',
  회원정보가_수정되었습니다: 'Member information has been updated',
  아직_회원이_아니십니까: 'Not a member yet?',
  ENJOY_YOUR_LIFE_ENJOY_YOUR_FARM: 'ENJOY YOUR LIFE, ENJOY YOUR FARM',
  조이팜과_함께_즐거운_농촌체험:
    'Enjoy a joyful rural experience with JoyFarm!',
  로그인: 'Login',
  JOYFARM_로그인: 'JOYFARM Login',
  // 마이페이지
  회원정보_수정_중_오류가_발생했습니다:
    'An error occurred while updating member information',
  회원_탈퇴가_완료되었습니다: 'Membership withdrawal completed',
  회원_탈퇴_중_오류가_발생했습니다:
    'An error occurred during membership withdrawal',
  회원정보_수정하기: 'Edit Member Information',
  회원정보_수정: 'Edit Member Information',
  회원탈퇴하기: 'Withdraw Membership',
  게시글_관리: 'Manage Posts',
  회원정보를_수정하시겠습니까:
    'Would you like to update your member information?',
  회원탈퇴를_진행하시겠습니까:
    'Would you like to proceed with membership withdrawal?',
  회원탈퇴완료: 'Membership Withdrawal Completed',
  회원탈퇴실패: 'Membership Withdrawal Failed',
  // 게시글
  조회된_게시글이_없습니다: 'No posts found',
  정말_삭제_하겠습니까: 'Are you sure you want to delete?',
  첨부파일_목록: 'Attachment List',
  댓글_목록: 'Comments List',
  여러분의_소중한_의견을_남겨주세요: 'Please leave your valuable opinion',
  // 추천 여행지
  추천_여행지: 'Recommended Travel Destination',
  추천_여행기간: 'Recommended Travel Period',
  여행지_설명: 'Travel Destination Description',
  여행지_찜하기: 'Bookmark Travel Destination',
  여행코스: 'Travel Course',
  여행장소: 'Travel Location',
  여행지_명: 'Travel Destination Name',
  인기_테마: 'Popular Theme',
  숲체험: 'Forest Experience',
  전통문화: 'Traditional Culture',
  텃밭체험: 'Garden Experience',
  휴양: 'Recreation',
  농촌_관광: 'Rural Tourism',
  힐링: 'Healing',
  테마파크: 'Theme Park',
  캠핑: 'Camping',
  여름휴가: 'Summer Vacation',
  건강: 'Health',
  체험: 'Experience',
  자연휴양림: 'Natural Recreation Forest',
  // 체험 예약
  농촌체험활동_예약: 'Rural Experience Reservation',
  체험활동_리스트: 'Experience Activity List',
  체험활동_예약: 'Experience Activity Reservation',
  체험활동_상세_정보: 'Detailed Information on Experience Activity',
  체험_프로그램_설명: 'Experience Program Description',
  체험_프로그램_소개: 'Introduction to Experience Program',
  보유시설정보: 'Facility Information',
  체험마을_주소: 'Experience Village Address',
  체험마을명: 'Experience Village Name',
  대표전화번호: 'Main Phone Number',
  예약_확인: 'Reservation Confirmation',
  님의_: 'Mr./Ms.',
  체험_활동_소개: 'Introduction to Experience Activity',
  체험_마을_대표자명: 'Representative Name of Experience Village',
  체험_마을_주소: 'Address of Experience Village',
  체험_마을_전화번호: 'Phone Number of Experience Village',
  예약일_선택: 'Select Reservation Date',
  예약자_기본정보: 'Basic Information of Reservant',
  예약시간_선택: 'Select Reservation Time',
  인원수_선택: 'Select Number of People',
  체험활동_조회: 'View Experience Activity',
  예약은_당일로부터_한달_이내만_가능합니다:
    'Reservations can only be made within a month from the day of reservation',
  // 예약 현황
  나의_예약_현황: 'My Reservation Status',
  예약_현황_리스트: 'Reservation Status List',
  예약내역_상세: 'Detailed Reservation History',
  예약_취소: 'Cancel Reservation',
  체험_마을명: 'Experience Village Name',
  예약한_체험_마을_정보: 'Information of Reserved Experience Village',
  예약자_정보: 'Reservant Information',
  예약자명: 'Reservant Name',
  예약자_전화번호: 'Reservant Phone Number',
  예약일: 'Reservation Date',
  예약시간: 'Reservation Time',
  예약인원: 'Number of People Reserved',
  예약한_체험_마을: 'Reserved Experience Village',
  체험_마을_세부정보_닫기: 'Close Detailed Information of Experience Village',
  체험_마을_세부정보_열기: 'Open Detailed Information of Experience Village',
  // 마이 페이지
  찜하기_리스트: 'Favorites List',
  조회된_게시물이_없습니다: 'No posts found',
};

export default commons;
